backup:
  downgrade: null
  enabled: false
  install: null
  mode: incremental
  remove_method: self
  type: rsync
  uninstall: null
  upgrade: null
boot:
  load_apps: true
disk:
  trim:
    after_upgrade: false
download:
  icons: true
  multithreaded: true
  multithreaded_client: null
gems:
- arch
- flatpak
locale: null
memory_cache:
  data_expiration: 3600
  icon_expiration: 300
store_root_password: true
suggestions:
  by_type: 10
  enabled: true
system:
  notifications: true
  single_dependency_checking: false
ui:
  auto_scale: true
  hdpi: true
  qt_style: fusion
  scale_factor: 1.0
  system_theme: true
  table:
    max_displayed: 100
  theme: darcula
  tray:
    default_icon: /usr/share/b-tray/def.png
    updates_icon: /usr/share/b-tray/upd.png
updates:
  ask_for_reboot: false
  check_interval: 60
